---
title: "Untitled"
author: "jacky wang"
date: "2020/4/27"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = T, eval=T)

# windows檔名不要有"-"號

```





# On numeric class

```{r}

a <- c(2, 3, 5)
b <- c(4,-1, 3)

```

```{r}

# elementwise operation

a+b
a-b
a*b
a/b

```

```{r}

a %% b    # 餘數

a ** b
a^b    # 次方

```

## practice

```{r}

# 奇、偶判斷

sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)

sequenceNums %% 2    # 餘數為1則是奇數，0則是偶數

```

## recycle (Python: broadcast)

```{r}

5 * c(1, 3, 4) + 7
# 等於
c(5,5,5) * c(1,3,4) + c(7,7,7)

```

```{r}

# 狀況一: 堆疊一定倍數剛好一樣長

c(2,3)/c(-2,-13,10,22)
# 等於
c(2,3,2,3)/c(-2,-13,10,22)

```

```{r}

# 狀況二: 倍數堆疊一定會超過，只好截斷

c(2,3)/c(-2,-13,10)
# 等於
c(2,3,2)/c(-2,-13,10)

```

```{r}

#rRecycle不只用在數值class

paste0(
  c("我叫"), c("小明","小美")
)
# 等於
paste0(
  c("我叫","我叫"), c("小明","小美")
)

```

```{r}

paste0(
  c("他叫","我叫"), c("小明","小美","大雄")
)

```





# Relational Operators

## 比較

```{r}

example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)

```

```{r}

str(example[c("name", "height")])

```

```{r}

# example裡誰的身高大於等於170

example$name[c(T, F, T, F)]    # 爛方法

example$height >= 170 -> pickAbove170
example$name[pickAbove170]


```

### practice1

```{r}

source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")

```

```{r}

str(transcript100to103)

```

```{r}

# 各學屆二年級人數

table(transcript100to103$學屆)    # 分類數次數


# contingency table: 列聯表

```

```{r}

# 選成績大於85分

transcript100to103$成績 > 85 -> pickAbove85
table(transcript100to103$學屆[pickAbove85])

```

### practice2

```{r}

example$birthday
class(example$birthday)
typeof(example$birthday)

```

```{r}

# example裡誰1998年（含）以後出生

print(example[c("name", "birthday")])

example$birthday >= lubridate::ymd("19980101") -> 
  pickAfter98
# typeof(example$birthday)
#   時間資料原始型態為double，可以比大小

example$name[pickAfter98]

```

### practice3

```{r}

source("https://www.dropbox.com/s/16h6ggua6qtydci/exchangeRate.R?dl=1")

```

```{r}

str(exchangeRate)

```


```{r}

# 選出1998年1月（含）以後的匯率資料

exchangeRate$期間 >= lubridate::ymd("19980101") -> 
  pickAfter1998

list(
  `期間` = exchangeRate$期間[pickAfter1998], 
  `幣別` = exchangeRate$幣別[pickAfter1998], 
  `匯率` = exchangeRate$匯率[pickAfter1998]
) -> 
  exchangeRate_after1998

```

### practice4

```{r}

print(example[c("name", "allowance")])

```

```{r}

# example裡誰零用錢大於1000

#example$allowance >= "1001-2000"    # not ordered factor
class(example$allowance)

```

```{r}

example$allowance <- 
  ordered(
    example$allowance
  )

class(example$allowance)
levels(example$allowance)

example$allowance >= "1001-2000" -> 
  pickOver1000

example$name[pickOver1000]

```

```{r}

# 也可以在設factor時直接設好ordered

factor(
  c("0-1000", "1001-2000", "2000+", "1001-2000"), 
  levels = c("0-1000", "1001-2000", "2000+"), 
  ordered = T    # 設定為可排序的factor
)

```

### homework

```{r}

jsonlite::fromJSON("https://www.dropbox.com/s/3uijub7xheib405/list_victimAges_female.json?dl=1", simplifyDataFrame = F) -> list_victimAges_female

```

```{r}

str(list_victimAges_female)
# View(list_victimAges_female$年齡層)

```

```{r}

# 選出「30_39歲以上受害者」的數目

library(dplyr)

# 設level向量
list_victimAges_female$年齡層 %>% 
  as.factor() %>% 
  levels() -> 
  levelOfAge

# 調成正確順序
levelOfAge_mod <- 
  levelOfAge[c(12, 13, 1, 8, 2:7, 9:11)]

# 更改 年齡層 為ordered
list_victimAges_female$年齡層 %>% 
  factor(
    levels = levelOfAge_mod, 
    ordered = T
  ) -> 
  list_victimAges_female$年齡層_ordered

list_victimAges_female$年齡層_ordered >= "30_39歲" -> 
  choose_above3039

list_victimAges_female$數目[choose_above3039] %>% 
  sum(na.rm = T)

```

## 相等、屬於

```{r}

example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)

```

```{r}

print(example[c("name", "bloodType")])

# example裡誰血型B型

pick_bloodB <- example$bloodType == "B"
example$name[pick_bloodB]

```

```{r}

sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)

# 取出偶數

pick_even <- (sequenceNums %% 2) == 0    # 確保()內先執行
sequenceNums[pick_even]

```

```{r}

x <- c(1,5,8)
y <- c(5,8)

x %in% y    # x裡的每個元素值是不是屬於y集合

```

```{r}

# example裡誰來自大台北

example[c("name", "residence")]

pick_fromTaipeiMetro <- example$residence %in% c("Taipei", "New Taipei")
example$name[pick_fromTaipeiMetro]

```

```{r}

source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")

str(transcript100to103)

```

```{r}

# 創造可選出來自法商學院的True or False向量

levels(factor(transcript100to103$學院))    # 看資料有哪幾種學院
unique(transcript100to103$學院)    # 看資料有哪幾種學院

pick_lawBusiness <- transcript100to103$學院 %in% c("法學院", "商學院")

```

## Negation

```{r}

# 在 TorF向量 前加上 ! 會成為否定句的 TorF向量

pick_notFromTaipeiMetro <- !pick_fromTaipeiMetro
pick_notFromTaipeiMetro <- !(example$residence %in% c("Taipei", "New Taipei"))

pick_notFromTaipeiMetro

example$name[pick_fromTaipeiMetro]
example$name[pick_notFromTaipeiMetro]

```

## 資料狀態

```{r}

x2 <- c(1, NA, 10)
y2 <- c(-1, NA, 20)

x3 <- c(NA, "小花")
y3 <- c(NA, "小華")

```

```{r}

is.na(x2)

```

```{r}

# NaN: not a number (出現在沒有定義的數學運算)

log(-10)

```

### practice1

```{r}

# example裡誰沒有體重資料

print(example[c("name","weight")])

choose_na <- is.na(example$weight)
example$name[choose_na]

```

### practice2

```{r}

jsonlite::fromJSON("https://www.dropbox.com/s/3uijub7xheib405/list_victimAges_female.json?dl=1", simplifyDataFrame = F) -> list_victimAges_female

```

```{r}

head(list_victimAges_female$數目)

# 創立可選出缺失資料的T/F向量, 並計算有多少筆缺失

is.na(list_victimAges_female$數目) -> pick_na
sum(pick_na)    # True=1, False=0

```

## 字元偵測

```{r}

example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)

```

```{r}

# example裡誰喜歡美食

print(example[c("name", "hobby")])

stringr::str_detect(example$hobby, pattern = "美食") -> pick_food
example$name[pick_food]
# str_detect(): 偵測字串內容內有無關鍵字（pattern）

```

### practice1

```{r}

jsonlite::fromJSON("https://data.ntpc.gov.tw/api/datasets/EDC3AD26-8AE7-4916-A00B-BC6048D19BF8/json") ->
  garbageRoutes

```

```{r}

typeof(garbageRoutes)    # 本質為list
class(garbageRoutes)    # class為data.frame表示它有比list多了許多操作空間

```

```{r}

# 由linename元素判斷垃圾車有幾條路線

# 資料損毀

```

## 閱讀函數說明

```{r}

library(stringr)
?str_detect

```

```{r}

# 看不懂說明，貼上範例試試

fruit <- c("apple", "banana", "pear", "pinapple")

str_detect(fruit, "a")
str_detect(fruit, "^a")    # 字元規律描述（regular expression）："^a"---以"a"開頭
str_detect(fruit, "a$")    # "a$"---"a"結尾 

str_detect(fruit, "a$", negate = T)
!str_detect(fruit, "a$")

str_detect(fruit, "b")
str_detect(fruit, "[aeiou]")

```

# homework

```{r}

CDC_chatbox <- readr::read_csv("http://od.cdc.gov.tw/pr/CDC_chatbox.csv")

```









