---
title: "Untitled"
author: "jacky wang"
date: "2020/3/25"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

# windows檔名不要有"-"號

```





# Atomic Vector Extended

## Factor

```{r}

majors10_char <- c('經濟學系', '社會學系', '社會學系', '經濟學系', '經濟學系', '社會學系', '經濟學系', '經濟學系', '經濟學系', '社會學系')

typeof(majors10_char)
class(majors10_char)


# 該資料應為類別資料

majors10_factor <- factor(majors10_char)

typeof(majors10_factor)    # 以整數形式儲存類別資料（電腦儲存資料的型態）
class(majors10_factor)

levels(majors10_factor)    # 不同電腦default的順序可能不同

```



```{r}

stringInteger <- c("1","2","-11")
class(stringInteger)
stringInteger+2    # 無法進行數值運算
as.numeric(stringInteger) + 2

trueInteger <- as.integer(stringInteger)
class(trueInteger)
typeof(trueInteger)
trueInteger+2    # 可以進行數值運算

```

### 練習

```{r}

studentId <- c(410773002, 410773015)

# 它目前是什麼class
class(studentId)    # numeric

# 學號用什麼class比較合理
as.character(studentId)    # character

```

## Date/Time class

```{r}

browseURL("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")

```

```{r}

library(lubridate)

```

```{r}

# 台北 2020-03-18 13:52:40
tpeTime <- ymd_hms("2020-03-18 13:52:40", tz = "Asia/Taipei"); tpeTime

typeof(tpeTime)    # 電腦儲存資料的形式
class(tpeTime)    # 電腦呈現資料的形式

# 葡萄牙 Mar.18, 2020, 05:52:40
ptTime <- mdy_hms("Mar.18, 2020, 05:52:40", tz = "Europe/Lisbon"); ptTime


# 兩地事實上是同時間
as.double(tpeTime)
as.double(ptTime)

```

```{r}

# List of Time Zones
browseURL(url = "https://en.wikipedia.org/wiki/List_of_tz_database_time_zones")

```


```{r}

# 轉成同時區
with_tz(tpeTime, tzone="UTC")
with_tz(ptTime, tzone="UTC")


# 小心以下兩函數的input中一個是tz，一個是tzone
#   ymd_hms(..., tz="Asia/Taipei")
#   with_tz(..., tzone="Asia/Taipei")

```

```{r}

ymd_hms("2020-03-04T06:56:29Z", tz = "Asia/Taipei")
ymd_hms("2020-03-04T06:56:29Z", tz = "Europe/Lisbon")
ymd_hms("2020-03-04T06:56:29Z")

# 若時間資料內有...T...Z，表示為UTC，不用刻意下時區
# （下了只會進一步轉成當地時間，多加一個步驟用with_tz()改較好）。

tpeTime2 <- ymd_hms("2020-03-04T06:56:29Z")

with_tz(
  time = tpeTime2, 
  tzone = "Asia/Taipei"
)

```

### 練習

```{r}

studentTime <- c(
  ymd_hms("2020-03-04T06:43:50Z"), 
  ymd_hms("2020-03-11 14:23:05", tz = "Asia/Taipei"), 
  ymd_hms("2020-03-11 14:39:57", tz = "Asia/Taipei")
  )

with_tz(
  studentTime, 
  tzone = "Europe/paris"
)

```

```{r}

c(
  ymd_hms("2020-03-04T06:43:50Z"), 
  ymd_hms(
    "2020-03-11 14:23:05", "2020-03-11 14:39:57",
    tz = "Asia/Taipei"
  )
)

```


