---
title: "Untitled"
author: "jacky wang"
date: "2020/4/12"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

# windows檔名不要有"-"號

```





# 選取一個元素

```{r}

vectorExample <- c("小明","小英","大雄")

# 有多少位置可選？
length(vectorExample)

# class(vectorExample)
# typeof(vectorExample)

```

## choose by position

```{r}

vectorExample[[1]]

```

```{r}

listExample <- 
  list(
    student="小明",
    semester=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )

# 有多少位置可選？
length(listExample)

```

```{r}

listExample[[1]]
listExample[[2]]

```

### practice

```{r}

library(jsonlite)

fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap

```

```{r}

tainanSportsMap[[1]]

tainanSportsMap[[1076]]

```

## choose by name

```{r}

# 有什麼名子可以選？
names(listExample)

# 查看原始資料結構
str(listExample)

str(listExample$semester)

```

```{r}

listExample$student
listExample$semester$`108-1`    # 特殊命名依然要用反頓點呼叫

```

```{r}

# 也可以用[["名字"]]來選

listExample[["student"]]
listExample$student

```

### practice

```{r}

fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002", simplifyDataFrame = F) -> newTaipeiCityVaccine

```

```{r}

str(newTaipeiCityVaccine)
length(newTaipeiCityVaccine)
names(newTaipeiCityVaccine)

```

```{r}

newTaipeiCityVaccine$success
newTaipeiCityVaccine[[1]]
newTaipeiCityVaccine[["success"]]

# 只顯示一層
str(newTaipeiCityVaccine[[2]], max.level = 1)

```

# 選取多個元素

## choose by position

```{r}

vectorExample
vectorExample[c(1, 3)]
vectorExample[c(3, 1, 2)]    # 產生重新排列的效果

```

```{r}

str(listExample, max.level = 1)
str(listExample[c(1, 2)], max.level = 1)
str(listExample[c(2, 1)], max.level = 1)

```

### practice

```{r}

# 任選數筆tainanSportsMap的運動地點

str(tainanSportsMap, max.level = 1)

str(tainanSportsMap[c(1, 35, 1006)], max.level = 1)

```

## choose by name

```{r}

# 顯示到第一層
str(listExample, max.level=1)

listExample[c("student", "semester")]
listExample[c("semester", "student")]

```

```{r}

listExample[["student"]]
listExample[c("student")]    # 不要用

```

### practice

```{r}

fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets

```

```{r}

# 任選幾個夜市元素出來

str(taipeiNightMarkets, max.level = 1)

taipeiNightMarkets[c("寧夏觀光夜市", "饒河街觀光夜市")]

```

## choose by logic vector

```{r}

vectorExample
vectorExample[c(T,T,F)]    # 要，要，不要
vectorExample[c(TRUE, TRUE, FALSE)]

```

```{r}

# 不要用

str(listExample[c(T, F)])
str(listExample[c("student")])

```


### practice

```{r}

# 用邏輯向量自taipeiNightMarkets選出
# 寧夏觀光夜市、西昌街觀光夜市、大龍街夜市、雙城街夜市。

str(taipeiNightMarkets, max.level = 1)
names(taipeiNightMarkets)

```

```{r}

library(dplyr)

taipeiNightMarkets[c(T, F, F, F, T, F, F, F, F, T, F, F, F, T)] %>% 
  str(max.level = 1)

```

```{r}

# 高級做法

selectedMarkets <- rep(F, 14)    # repeat函式
print(selectedMarkets)

selectedMarkets[c(1, 5, 10, 14)] <- TRUE    # 取代
print(selectedMarkets)

taipeiNightMarkets[selectedMarkets] %>% 
  str(max.level = 1)

```

# why don't use the [c("XXX")] method? 

```{r}

str(listExample, max.level = 3)

```
```{r}

get1 <- listExample[["semester"]]
str(get1, max.level = 1)

```

```{r}

get2 <- listExample[c("semester")]
str(get2, max.level = 1)
str(get2, max.level = 2)

```

```{r}

str(get1, max.level = 1)
str(get2, max.level = 1)

# [[]]：拿出某個物件值。
# listExample[["semester"]]將listExample裡的“semester”物件值拿出來

# []: 留下某個物件值。
# listExample[c("semester")]「只留下」listExample裡的“semester”物件值

```

# 連鎖選取

```{r}

numVector <- c(2,3,6,-1,4,2,6)
select1 <- numVector[c(1,4)]; select1
select2 <- select1[[1]]; select2

# 相當於

numVector[c(1,4)][[1]]

```

```{r}

# 用 ; 斷行

select1 <- numVector[c(1,4)]
select1

select1 <- numVector[c(1,4)]; select1

```

```{r}

select1 <- numVector[c(T,T,F,T,F,F,T)]; select1
select2 <- select1[c(1,4)]; select2

# 相當於
numVector[c(T,T,F,T,F,F,T)][c(1,4)]

```

## practice

```{r}

majors <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F", "F", "M", "F", "M")

```

```{r}

# 創造出只要“經濟學系”學生的邏輯向量



```










