---
title: "Untitled"
author: "jacky wang"
date: "2020/5/29"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = T, eval=T)

# windows檔名不要有"-"號

```





# On logical class

邏輯運算符號：
  &: AND
  |: OR

```{r}

example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)

```

```{r}

pick_above170 <- example$height >= 170

pick_bloodB <- example$bloodType == "B"

pick_loveFood <- 
  stringr::str_detect(example$hobby, "美食")

pick_na <- is.na(example$weight)

pick_after98 <- 
  example$birthday >= lubridate::ymd("1998-01-01")

set_TaipeiMetro <- c("Taipei", "New Taipei")

pick_fromTaipeiMetro <- 
  example$residence %in% set_TaipeiMetro

```

```{r}

# 誰喜歡美食且血型為B型

str(example[c("name", "hobby", "bloodType")])

example$name[pick_loveFood & pick_bloodB]

```

```{r}

# 誰1998以後出生或不住大台北

str(example[c("name", "birthday", "residence")])

example$name[pick_after98 | !pick_fromTaipeiMetro]

```





# On character class

```{r}

library(stringr)
library(glue)

```

```{r}

str_sub("410873002", 5, 6)

str_sub(
  c("410873002", "410552103"), 5, 6
)

```

```{r}

# 地址幾號？只知道號碼在「號」這字前面，但它會是第幾個位置不知道。
# 如何讀入“民國X年X月X日”？

library(lubridate)

ymd("民國108年12月5日", "民國98年10月5日")    # lubridate對年只有西元年的概念

ymd(
  c(
    "民國2019年12月05日", 
    "馬丁2019的12課05muydifícil", 
    "助教2019Emily12解說05真棒", 
    "2019R12課程05すごい", 
    "R程式2019的12期中考05とても変態"
  )
)

```

## Regular expression (regex)

target pattern：
  0~9的字元，2~3個字元：[:digit:]{2,3} 或 [0-9]{2,3}
  
target location description：
  "民國98年"，target pattern前面是「民國」後面是「年」：(?<=民國)[0-9]{2,3}(?=年)

```{r}

str_extract_all(
  string = c("民國108年12月5日","民國98年10月5日"),
  pattern = "(?<=民國)[0-9]{2,3}(?=年)"
)    # 回傳list

str_extract(
  string = c("民國108年12月5日","民國98年10月5日"),
  pattern = "(?<=民國)[0-9]{2,3}(?=年)"
)    # 回傳vector

```

### 固定字元／組

單一出象

```{r}

heartSutra <- c("舍利子，色不異空，空不異色；色即是空，空即是色。")

str_view_all(heartSutra,"色")    # 檢視
str_count(heartSutra,"色")    # 計數

str_view_all(heartSutra,"異色")

```

### 多個字元／組

多個出象，用(...|...|...)

```{r}

studentIds <- c("410873029", "410773005", "410772035", "410562123", "410473108")
# 第5筆不小心被選出來了

# 取出學號中的入學屆為107或108

str_view_all(studentIds,"(107|108)")
str_view_all(studentIds, "107|108")    # 可不寫()，若前後沒有接其他描述

# 是否來自107或108學屆
str_detect(studentIds, "107|108")

```

### 字「元」組合

eg. [af78]：可以產生a、f、7、8四種字元出象
eg. [^趙錢孫李]：不能有趙、錢、孫、李任何一個

常見的字元模版：[0-9]或[:digit:]、[a-z]或[:lower:]

```{r}

Ids <- c("A283743192","B829103720","A10920402","C291022384")

str_view_all(Ids, "[AC]")
str_detect(Ids, "[AC]")
str_extract(Ids,"[A-Z]")    # 取出 A-Z 的字元

```

### example

```{r}

strip1 <- "[0-9]"
strip2 <- "(櫻桃|777|紅心)"    # 字群組合strip因為等下放中間所以用()括起來
strip3 <- "[A-Z]"

myRegexSlotMachine <- paste0(strip1, strip2, strip3)
print(myRegexSlotMachine)

```

```{r}

claimA <- "我得到A檸檬99"
claimB <- "我的是7777Z"
claimC <- "我玩了兩次，一次是7蘋果H，另一次是5紅心J"

# 顯示吻合的出象

str_view(
  c(claimA, claimB, claimC), 
  pattern = myRegexSlotMachine
)

# 是否有吻合的出象

str_detect(
  c(claimA, claimB, claimC), 
  pattern = myRegexSlotMachine
)

```

#### practice1

```{r}

headline <- "資科系的謝陳官乃飛鳶書院三大名師，其中謝無雙的策略運算，陳大器的數理資科學，及官求敗的運算成本更是打通演算思維任督二脈的三大好課。書院目前有陳一、陳二、陳三四這三名學生。"

```

```{r}

# 顯示固定字組"謝陳官"

str_view_all(
  string = headline, pattern = "謝陳官"
)

# 顯示字元組合謝、陳、官

str_view_all(
  string = headline, pattern = "[謝陳官]"
)

# 顯示多個字組謝無雙、官求敗

str_view_all(
  string = headline, pattern = "謝無雙|官求敗"
)

# 顯示固定字組"陳X"，但"X"不是"官"

str_view_all(
  string = headline, pattern = "陳[^官]"
)

```

#### practice2

```{r}

addresses <- c(
  '臺中市后里區公館里尾社路385號',
  '新竹市東區科學園路125號1樓'
)

```

```{r}

# 請使用str_extract()取出每個地址的"xx號"包含"號"字。

jac1 <- jac2 <- jac3 <- "[0-9]"    # 同時產生多個相同的object
jac4 <- "號"

regexStatement <- paste0(jac1, jac2, jac3, jac4)
regexStatement

str_extract(addresses, regexStatement)

```

```{r}

# 另解

str_extract(
  addresses, 
  "[:digit:]+(?=號)號"
)

```








